### ISSUE TITLE
State corruption with scalarset?

### ISSUE THREAD

**Issue by nwf** [Smattr/rumur#193] opened 2020-06-11 16:16 UTC
I've got a (fairly complex) model of a CPU TLB and page table and a little bit of OS logic to spot-check some properties.  It seems to verify fine (and finds counterexamples when I add them), but I was naive when I wrote it and it has a large state space with ordered arrays, which is not great, so I thought I'd move to scalarset-indexed arrays...

So I tried, but I am seeing some truly weird behavior now, with errors reported that (I think) can't possibly happen, making me think there's some in-`rumur` state corruption.

Thank you for all your hard work on `rumur` and please let me know how I can further assist.  I've tried to write smaller examples of what I thought might be tickling the bug, but those all work fine.  I'll update below when/if I get a self-contained minimal model that still hits the issue(s).

### Ruleset-quantified variable corruption?

One that might just be a reporting bug looks like this part of an invariant failure report:
```
Rule "PTE map", pix: 0 fired.
pt[1].mapped:true
```

note the `0` selected by the ruleset but `1` reported for the index in state changes.  The rule body is

```
ruleset
  pix : alias_ix_t
do
  -- ... other rules elided

  rule "PTE map"
    !pt[pix].mapped & !mi.xbusy
  ==>
    pt[pix].mapped := true;
    -- ...
  endrule
endruleset
```

with

```
const n_pte : 2;
type alias_ix_t : scalarset(n_pte);
```

### Incorrect state vector update

Increasing the size of the model (so that `const n_pte : 5`) can trigger

```
read of undefined value in mi.xbusy_cd within rule "revoke visit end"
```

but the error trace ends with

```
Rule "PTE populate revoke", pix: 5 fired.
pt[5].valid:true
pt[5].capdirty:false
pt[5].capstore:false
pt[5].clgmatch:false
mi.xbusy:true
mi.xbusy_cd:true
mi.xbusy_pix:0
----------

Rule "revoke visit end" fired.
pt[5].clgmatch:true
----------
```

which indicates that `mi.xbusy_cd` was just set by the previous transition, as expected (but `mi.xbusy_pix` does not look correct).

The rules here are kind of hairy, but paring things down a bit, here's (I think) the relevant chunks of the code:

```
procedure BeginVisit(pix : alias_ix_t)
  mi.xbusy_pix := pix;
  mi.xbusy_cd  := page_tag_count > 0;
  mi.xbusy     := true;
endprocedure

ruleset
  pix : alias_ix_t
do
  -- ...

  rule "PTE populate revoke"
    mi.revoking & !mi.xbusy & pt[pix].mapped & !pt[pix].valid
  ==>
    -- ...
    BeginVisit(pix);
  endrule

  -- ...
endruleset

rule "revoke visit end"
  mi.xbusy
==>
  if !pt[mi.xbusy_pix].valid then
  -- ...
  elsif pt[mi.xbusy_pix].clgmatch then
  -- ...
  else
    -- ...
    if mi.xbusy_cd | mi.capdirty then
    -- ...
  --...
endrule;
```

`BeginVisit` is the only mechanism for `mi.xbusy` to become `true`, and it always sets `mi.xbusy_pix` and `mi.xbusy_cd`.

**Comment by nwf** [comment] 2020-06-11 17:15
In trying to minimize my model, I found an assertion:

```
$ rumur-run -d -t 1 ./min.murphi
Generating the checker...
parsing input model...
re-indexing...
resolving symbols...
validating AST...
optimising field ordering...
determining value_t type...
increasing maximum numerical bound to 4 due to "4"
considering type uint8_t...
using numerical type uint8_t as value type
generating verifier...
Compiling the checker...
Running the checker...
Memory usage:

        * The size of each state is 31 bits (rounded up to 4 bytes).
        * The size of the hash table is 65536 slots.

        * state struct is 1-byte aligned
        * field pt is located at state offset 7 bits
        * field mi is located at state offset 0 bits

Progress Report:

a.out: <stdin>:1649: decode_value: Assertion `!r && "read of out-of-range value"' failed.
```

The complete model that produces the above is:

```
const n_pte      : 4;

type pte_t : record
  mapped   : boolean;
  visited  : boolean;
  valid    : boolean;
endrecord;

type alias_ix_t : scalarset(n_pte);

var mi  : record
  xbusy     : boolean;
  xbusy_pix : alias_ix_t;
  xbusy_cd  : boolean;
endrecord;

var pt  : array [ alias_ix_t ] of pte_t;

startstate "INIT"
  mi.xbusy    := false;
  for ix : alias_ix_t do pt[ix].mapped := false; endfor;
endstartstate

ruleset
  pix : alias_ix_t
do
  rule "PTE populate revoke"
    !mi.xbusy & pt[pix].mapped & !pt[pix].valid
  ==>
    mi.xbusy_pix  := pix;
    mi.xbusy      := true;
  endrule

  rule "PTE map"
    !pt[pix].mapped & !mi.xbusy
  ==>
    pt[pix].mapped := true;
    pt[pix].valid := false;
  endrule
endruleset

rule "revoke visit end"
  mi.xbusy
==>
  if !pt[mi.xbusy_pix].valid then endif;
  mi.xbusy := false;
endrule
```

In trying to further minimize it, I observed that
* reducing `n_pte` below 4 makes the assertion failure go away
* swapping the order of `xbusy_pix` and `xbusy_cd` within the `mi` structure also makes the assertion go away.

I forgot to say, above, that all of this is tested on Debian ppc64le with `rumur` `v2020.05.27-10-g4944427`.

**Comment by Smattr** [comment] 2020-06-12 00:26
Thanks for the detailed report! Always nice to hear from users, though I'm sorry it's because Rumur isn't working correctly.

I think there's actually three separate issues here:
1. Strange counterexample values when using scalarsets. Coincidentally another user reported this privately to me today too. This was actually something known to me and is not exactly a bug, but related to the way symmetry reduction is implemented. The state values in the trace are *after* symmetry reduction, while the ruleset values are *before*. I.e. in your example, symmetry reduction swapped the `0` and `1` values of the `alias_ix_t` type, hence the discrepancy. This is a nice story but it doesn't really help you, does it? You're still stuck looking at confusing counterexample traces. I'll work on resolving this to something more natural like what Rumur's predecessor CMurphi does. Unfortunately in the meantime the only workaround I can offer is to turn off symmetry reduction or try to do the described remapping in your head :(
2. The "incorrect state vector update." I don't quite understand what the expected behaviour here was, so I'm not sure what has actually gone wrong. Maybe this is the issue you've minimised to the assertion failure in your last message?
3. The assertion failure. Clearly a bug. I don't know offhand what the cause is, but I can reproduce this one locally so I'll post an update when I've debugged it further.

I should mention that Rumur has not been heavily tested on ppc64le. I do all testing and development on x86-64, though I don't see how this difference could be the cause of any of the above issues.

**Comment by nwf** [comment] 2020-06-12 01:15
@Smattr It's been working great for a while and I'm sorry I'm only contacting you now to bring the bad news.

1. Ah ha, that makes sense and *is* a nice story, indeed.  I'll add a comment about reading the symmetry-reduced traces to the model's prose commentary.  I think focusing on the rule firings will give enough of a hint as to what (if anything) has gone wrong.

2. Sorry to have been unclear.  In my model's state vector, I'm trying to encode one of two sub-states:
    * The modelled object is not "exclusively busy" (`xbusy`), and so `xbusy` is `false` and `xbusy_pix` is `undefined`.  This is the initialization state.
    * The modelled object *is* `xbusy`, so `xbusy` is true and `xbusy_pix` is set to the (`ruleset`-quantified scalarset-typed) index which busied it.

`BeginVisit` is the only way to move from the first of those sub-states to the second (in particular, it is the only place in the model that `xbusy` gets set to `true`) and always assigns both `xbusy` and `xbusy_pix`.  Dually, the only way back, though not shown in the example, is the "revoke visit end" rule, which, in the end, sets `xbusy` to `false` and undefines `xbusy_pix`.

Therefore, I expect that any rule predicated on `xbusy` being `true`, such as "revoke visit end", will never see an undefined value for `xbusy_pix`, but yet `rumur` is claiming that that happened.  Examining the trace, `xbusy_pix` was just set to 0 (post symmetry-reduction) and so, I think, shouldn't be seen as undefined within the body of the "revoke visit end" rule.  Knowing essentially nothing about the internals of `rumur`, I would be inclined to look for some case where the wrong state `handle` was used, but that may be _completely_ off the mark.

3. I'm glad it reproduced for you!  I was, I admit, a little worried that it was going to be some peculiarity of ppc64le.  But it happens that this ppc box is the only machine I have with enough RAM to run the full model; I'm hoping that symmetry reduction helps with that.

**Comment by Smattr** [comment] 2020-06-12 02:24
I haven't fully root caused the assertion failure, but it appears to be related to record field reordering, commit 2cb30e7c675d08837c26e0e204fa9f8457c40053. Unfortunately there's no command line option to disable this because I (foolishly) did not anticipate that this could cause problems. If you're comfortable building from source, this patch may work around it for now:

```diff
diff --git rumur/src/main.cc rumur/src/main.cc
index f4df2ea8..0a93cc2e 100644
--- rumur/src/main.cc
+++ rumur/src/main.cc
@@ -641,9 +640,11 @@ int main(int argc, char **argv) {
     }
   }

+#if 0
   // re-order fields to optimise access to them
   *debug << "optimising field ordering...\n";
   optimise_field_ordering(*m);
+#endif

   // get value_t to use in the checker
   *debug << "determining value_t type...\n";
```

Stay tuned for more complete fix...

**Comment by Smattr** [comment] 2020-06-12 04:48
Well the assertion failure managed to be an impressive combination of three different bugs:
1. state variable offsets were not updated during reordering (fixed in 3d8e551bf1c4873d570dc0a8adac7f52c0b9ea25);
2. fields within records attached to identifiers were not reordered (fixed in cf03554574c7fd2fa78d461fbae95b97624b6f78); and
3. fields within records attached to type identifiers are not reordered (unfixed).

The fix for (3) is not complicated, but I need to think about how to construct a test case to exercise this first. Are you able to test if the changes currently in master get you past your immediate obstacle?

Given this field reordering optimization turned out to not at all be as "trivial" as I thought, I want to introduce a command line option for disabling it in the next release. You should have no reason to disable it if it's working correctly, but this issue demonstrates there are some subtle  interactions with it and other features.

**Comment by nwf** [comment] 2020-06-12 05:27
Yes, 5e184af no longer crashes nor aborts with the `read of undefined value` error; thanks!

Now to debug my model a bit, I think.

P.S., `rumur-run` might be better served by preferring the `rumur` next to it rather than the generic one in $PATH.  I was thrown for a bit trying to check on `master` because it kept running the `rumur` in `/usr/bin`!

**Comment by Smattr** [comment] 2020-06-12 13:58
Excellent!

> rumur-run might be better served by preferring the rumur next to it

Hm, yes, not sure what motivated the existing behaviour but I'll switch it for the next release.

**Comment by Smattr** [comment] 2020-06-14 02:08
Reading this back, I think the "Incorrect state vector update" issue could have been caused by the same field reordering problem. I've just pushed the last part of the fix that takes care of number (3) from my previous list, in commit 8b74668. Does this solve the `xbusy` confusion as well?

If so, then I think the only remaining issue is the confusing counterexample traces with scalarsets.

**Comment by Smattr** [comment] 2020-07-12 21:54
Sorry it took a while to make progress on this, but I think I've got something workable in the branch "feature/scalarset-remapping3". Are you able to try this out?

In that branch, scalarset values in counterexample traces and `put` statements are printed symbolically. So, if you have a `foo: scalarset(4)`, its values will be printed as `foo_0`, `foo_1`, `foo_2`, `foo_3`.

I'm still not quite satisfied with this solution. It works (AFAICT), but some testing suggests to me it has ~18% performance degradation in the runtime of large models. If I can't improve this, I think I'll have to expose a flag to switch it off and fall back to the confusing output for those who need runtime performance.

**Comment by nwf** [comment] 2020-07-12 23:10
No worries!  I'll find some time this week to give it a whirl.  Thank you, again, for all your hard work on `rumur`.

I think, given that this matters only in the case of found counterexamples, that the "run without and if things blow up run with" is a perfectly reasonable flow.  If there's other work you'd rather be spending time on, don't prioritize optimizing error reporting. :)

**Comment by Smattr** [comment] 2020-07-13 01:53
Thank you, that's very kind to say.

Actually this is basically priority number one at this point ;) I have yourself and two corporate users asking about this. The performance implications may be irrelevant for many users. However, I'm very sensitive to any performance regressions. I know of some corporate models that take 24+ hours to run, so an 18% increase in this is undesirable. Rumur does quite a lot of gymnastics to get its performance (bit-packing structures, lock-free concurrent data structures, self-managed allocation, ...), so it would be a shame to lose some of these gains.

The scalarset in your example is of size 4. The scalarsets I see in other models are also typically ≤ 4. This makes sense to me because they're often used to model something like threads or symmetric resources, and once you have a race that requires more than 4 entities to produce it's often a sign that your design is too complicated for any human to understand. I bring this up because I'm considering an optimization that involves unrolling a loop when dealing with a scalarset of maximum 4. I do not yet know whether this "optimization" will actually make a difference, but would you say you're usually specifying scalarsets of maximum 4? I'm thinking if a scalarset of > 4 is expensive, but in practice nobody uses these anyway, it's not such a big deal to have this feature always on.

**Comment by Smattr** [comment] 2020-07-19 01:48
Update on this: I tried my unrolling optimisation and it had no significant impact :( So I'm going to work towards merging this as an optional (default on) feature.

**Comment by Smattr** [comment] 2020-07-30 03:05
I'm merged these changes to master and cut a new release, v2020.07.28. Let me know if there's still problems that need addressing. And thanks again for reporting this!

**Closed by Smattr** 2020-07-30 03:05 UTC
Labels: bug
