### ISSUE TITLE
Tests fail: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 120: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [Smattr/rumur#134] opened 2019-06-03 01:46 UTC
```
Traceback (most recent call last):
  File "/usr/ports/math/rumur/work/rumur-2019.06.01/tests/integration-tests.py", line 434, in <module>
    sys.exit(main(sys.argv))
  File "/usr/ports/math/rumur/work/rumur-2019.06.01/tests/integration-tests.py", line 363, in main
    option.update(parse_test_options(m, False)) # <- False used as dummy arg
  File "/usr/ports/math/rumur/work/rumur-2019.06.01/tests/integration-tests.py", line 77, in parse_test_options
    for line in f:
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 120: ordinal not in range(128)
*** Error code 1
```

Version: 2019.06.01
FreeBSD 12
python-3.6

**Comment by Smattr** [comment] 2019-06-03 02:25
Thanks for the report. Can I ask what your locale is (`echo ${LANG}`)? I'm guessing from the traceback that it is a non-UTF-8 one. Perhaps we should be suppressing UTF-8 tests when the users locale does not support it.

**Comment by yurivict** [comment] 2019-06-03 02:43
```LANG``` isn't set in the environment.

```
$ env | grep -i lc
LC_CTYPE=en_US.UTF-8
```

**Comment by Smattr** [comment] 2019-06-04 02:59
I just noticed [you're packaging this for FreeBSD](https://svnweb.freebsd.org/ports/head/math/rumur/). Thank you! Something I had thought about but not gotten around to.

I reproduced the issue on FreeBSD 12 and realised a few other things were broken too. Unfortunately I don't regularly test on FreeBSD because Travis CI doesn't support it. I've been eyeing alternatives like Cirrus CI but I don't have any past experience with it.

Can you have a look at what I've pushed to the bugfix/github-134 branch and see if it works for you? If you want to see more information about what the test suite is up to while it's running, instead of running `make test` you can run `python3 /path/to/source/dir/tests/integration-tests.py --verbose`.

**Comment by yurivict** [comment] 2019-06-04 05:26
> I just noticed you're packaging this for FreeBSD. Thank you! Something I had thought about but not gotten around to.

You're welcome!

> Can you have a look at what I've pushed to the bugfix/github-134 branch and see if it works for you?

It works, thanks!

**Comment by Smattr** [comment] 2019-06-05 02:36
Great! I've merged this to master now.

Rumur has no particular release schedule, so I was going to cut a new release now. However, I noticed that you're using shebangfix for the FreeBSD package. Is there a more compatible way I could write the Python shebangs to ease your work by removing this dependency?

**Comment by yurivict** [comment] 2019-06-05 04:09
> Rumur has no particular release schedule, so I was going to cut a new release now. However, I noticed that you're using shebangfix for the FreeBSD package. Is there a more compatible way I could write the Python shebangs to ease your work by removing this dependency?

Thanks for offering! ```shebangfix``` is because "python" can be resolved in multiple ways. It patches ```rumur/src/rumur-run``` and ```tests/integration-tests.py``` for the version of python set by ```USES=python``` which is currently ```/usr/local/bin/python3.6```. I don't think anything can be done on your side for this, ```shebangfix``` corrects them just fine.

So please feel free to make a release. With tests working the port now is in a perfect shape! :-)

**Comment by Smattr** [comment] 2019-06-05 04:34
Excellent. I've just pushed new release notes to master and I'll tag the tip when the Travis CI tests pass.

**Comment by Smattr** [comment] 2019-06-06 00:13
Done and tagged. Let me know if you have any further problems and thanks again for the packaging work!

**Closed by Smattr** 2019-06-06 00:13 UTC

**Comment by yurivict** [comment] 2019-06-06 05:10
I updated the port, thank you!
